version: "3"

services:
  camera:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/camera:1.1.2
    container_name: camera
    restart: always
    environment:
      - host=10.10.10.10
      - user=admin
      - pwd=
    labels:
      - traefik.enable=true
      - traefik.http.port=9000
      - traefik.http.frontend.rule=Method:GET,POST,PATCH,PUT,DELETE;PathPrefix:/api/v2/camera
      - traefik.http.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.frontend.rule=PathPrefix:/cameraService.CameraService
    volumes:
      - /etc/localtime:/etc/localtime:ro
