version: "3"

services:
  camera:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/camera:1.1.2
    container_name: camera
    restart: always
    environment:
      - host=10.10.10.10
      - user=admin
      - pwd=
    volumes:
      - /etc/localtime:/etc/localtime:ro
