version: "3"

services:
  camera:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/camera:1.0.2
    container_name: service-camera
    restart: always
    environment:
      - module=xm
      - dvr=0
      - dvr_store_days=7
      - host=10.10.10.10
      - user=admin
      - pwd=
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.backend=camera
      - traefik.frontend.rule=PathPrefix:/api/v2/camera
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/jjrobot/dvr:/dvr
