version: "3"

services:
  db:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/mongo:4.0.5
    container_name: robot-db
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=robotjj
    - MONGO_INITDB_ROOT_PASSWORD=ROBOTjjROBOT
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/jjrobot/jdb_mgo:/data/db
  redis:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/redis:5.0.3
    container_name: robot-redis
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  frpc:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/frpc:1.1.0
    container_name: robot-frpc
    restart: always
    network_mode: host
    volumes:
    - /etc/localtime:/etc/localtime:ro
  auth:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/auth:1.1.0
    container_name: robot-auth
    restart: always
    environment:
    - jwt_timeout_sec=604800
    - PASSWORD=123456
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/jjrobot/certs:/certs
  gateway:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/gateway:2.6.3
    container_name: robot-gateway
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/jjrobot/certs:/certs
    ports:
    - 80:80
    - 443:443
  management-pages:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/management-pages:2.7.3
    container_name: management-pages
    restart: always
  gateway-envoy:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/gateway_envoy:1.0.0
    container_name: robot-gateway-envoy
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/jjrobot/certs/fullchain.pem:/certs/crt.pem
    - /var/lib/jjrobot/certs/privkey.pem:/certs/key.pem
    ports:
    - 8000:8000
  ws_gateway:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/ws_gateway:2.4.0
    container_name: robot-ws-gateway
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  messaging:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/messaging:1.0.3
    container_name: robot-messaging
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  import-export:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/import_export:1.2.0
    container_name: robot-import-export
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  kms:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/kms:latest
    container_name: robot-kms
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/jjrobot/dvr:/dvr
    environment:
      - KMS_TURN_URL=test:abc@119.23.254.113:3478
  webrtc-server:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/webrtc-server:1.1.0
    container_name: robot-webrtc-server
    restart: always
    environment:
      - KMS_WS_URI=ws://10.10.10.2:8888/kurento

networks:
  default:
    external:
      name: robotnet
