version: "3"

services:
  db:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/mongo:4.0.5
    container_name: db
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=robotjj
    - MONGO_INITDB_ROOT_PASSWORD=ROBOTjjROBOT
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/jjrobot/jdb_mgo:/data/db
  redis:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/redis:5.0.3
    container_name: robot-redis
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  frpc:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/frpc:1.1.0
    container_name: frpc
    restart: always
    network_mode: host
    volumes:
    - /etc/localtime:/etc/localtime:ro
  robotproxyv2:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/robotproxyv2:1.1.0
    container_name: robotproxyv2
    restart: always
    network_mode: host
  auth:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/auth:1.2.0
    container_name: auth
    restart: always
    environment:
    - jwt_timeout_sec=604800
    - PASSWORD=123456
    - HTTP_URI_VALID_PREFIXES=/api/,/daemon/api/,/service/ws
    - HTTP_URI_VALID_IGNORED=/daemon/api/v1/info
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/jjrobot/certs:/certs
  api-doc:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/api-doc:1.3.2
    container_name: api-doc
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
  gateway:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/gateway:2.8.1
    container_name: gateway
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/jjrobot/certs/fullchain.pem:/certs/fullchain.pem:ro
    - /var/lib/jjrobot/certs/privkey.pem:/certs/privkey.pem:ro
    ports:
    - 80:80
    - 443:443
    - 81:81
    - 8000:8000
    - 8001:8001
  management-pages:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/management-pages:2.10.1
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/management-pages:2.10.0-face-arc.alpha.2
    container_name: management-pages
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
  ws_gateway:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/ws_gateway:2.4.0
    container_name: ws_gateway
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  messaging:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/messaging:1.0.5
    container_name: messaging
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  import-export:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/import_export:1.2.0
    container_name: import-export
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
  kms:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/kms:latest
    container_name: kms
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/jjrobot/dvr:/dvr
    environment:
      - KMS_TURN_URL=test:abc@119.23.254.113:3478
  webrtc-server:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/webrtc-server:1.1.1
    container_name: webrtc-server
    restart: always
    depends_on:
      - kms
    environment:
      - KMS_WS_URI=ws://10.10.10.2:8888/kurento
    volumes:
      - /etc/localtime:/etc/localtime:ro
  kvstore:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/kvstore:1.1.0
    container_name: kvstore
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/jjrobot/kvstore:/db
  aging-test-service:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/agingtestservice:1.0.1
    container_name: aging-test-service
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
  aging-test-pages:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/agingtestpages:1.0.0
    container_name: aging-test-pages
    restart: always
  audiovideo:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/audiovideo:1.0.2
    container_name: audiovideo
    network_mode: host
    restart: always
    environment:
      - RTSP_AV_MAIN=
      - RTAP_V_NAV=
      - V4L2_V_NAV=/dev/video0
      - MAIN_VIDEO_WIDTH=640
      - MAIN_VIDEO_HEIGHT=360
      - MAIN_VIDEO_FRAMERATE=20
      - MAIN_VIDEO_BITRATE=150000
      - NAV_VIDEO_WIDTH=640
      - NAV_VIDEO_HEIGHT=360
      - NAV_VIDEO_FRAMERATE=15
      - NAV_VIDEO_BITRATE=100000
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
  audiovideogw:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/audiovideo-gw:1.0.0
    container_name: audiovideogw
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    external:
      name: robotnet
