version: "3"

services:
  esc_pos:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/esc_pos:2.0.0
    container_name: service-esc-pos
    restart: always
    environment:
      - module=sprt
    volumes:
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/jjep:/dev/jjep
