version: "3"

services:
  expression:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/expression:1.2.1
    container_name: expression
    restart: always
    depends_on:
      - gserial-head
    labels:
      - traefik.enable=true
      - traefik.http.port=9000
      - traefik.http.frontend.rule=Method:GET,POST,PATCH,PUT,DELETE;PathPrefix:/api/v2/expression
      - traefik.http.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.frontend.rule=PathPrefix:/expressionService.ExpressionService
    volumes:
      - /etc/localtime:/etc/localtime:ro
  gserial-head:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/grpc_serial:1.1.1
    container_name: gserial-head
    restart: always
    devices:
      - /dev/ttyHead:/dev/ttyHead
    ports:
      - 127.0.0.1:28053:8000
    command: ["-device", "/dev/ttyHead", "-protocol", "jjrobot", "-log", "info"]
  fileman-el:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/fileman:1.1.2
    container_name: fileman-el
    restart: always
    volumes:
      - /media/jjrobot-le-media:/storage
    environment:
      - ROOT=/storage
