version: "3"

services:
  expression:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/expression:1.2.1
    container_name: expression
    restart: always
    depends_on:
      - hwdevice-head
    labels:
      - traefik.enable=true
      - traefik.http.port=9000
      - traefik.http.frontend.rule=Method:GET,POST,PATCH,PUT,DELETE;PathPrefix:/api/v2/expression
      - traefik.http.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.frontend.rule=PathPrefix:/expressionService.ExpressionService
    volumes:
      - /etc/localtime:/etc/localtime:ro
  hwdevice-head:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/hwdevice:1.0.0
    container_name: hwdevice-head
    restart: always
    environment:
      - COMPATIBLE=1
    devices:
      - /dev/ttyHead:/dev/ttyHWDevice
    labels:
      - traefik.enable=true
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.frontend.rule=PathPrefix:/hwdevice;Host:head
  fileman-el:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/fileman:1.1.2
    container_name: fileman-el
    restart: always
    volumes:
      - /media/jjrobot-le-media:/storage
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ROOT=/storage
