version: "3"

services:
  expression:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/expression:1.3.0
    container_name: expression
    restart: always
    depends_on:
      - hwdevice-head
    volumes:
      - /etc/localtime:/etc/localtime:ro
  hwdevice-head:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/hwdevice:1.0.1
    container_name: hwdevice-head
    restart: always
    environment:
      - COMPATIBLE=1
    devices:
      - /dev/ttyHead:/dev/ttyHWDevice
  fileman-el:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/fileman:1.1.2
    container_name: fileman-el
    restart: always
    volumes:
      - /media/jjrobot-le-media:/storage
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ROOT=/storage
