version: "3"

services:
  expression:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/expression:2.0.0
    container_name: expression
    restart: always
    depends_on:
      - hwdevice-head
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/jjrobot/expressionV2:/expressionV2
    environment:
      - GODEBUG=netdns=cgo
      - ROOT=/expressionV2
      - FRAME_DURATION=100
  hwdevice-head:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/hwdevice:1.0.5
    container_name: hwdevice-head
    restart: always
    privileged: true
    environment:
      - COMPATIBLE=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyACM0:/dev/ttyHWDevice
