version: "3"

services:
  expression:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/expression:1.2.1
    container_name: service-expression
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.backend=expression
      - traefik.frontend.rule=PathPrefix:/api/v2/expression
    volumes:
      - /etc/localtime:/etc/localtime:ro
  gserial-head:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/grpc_serial:1.1.0
    container_name: gserial-head
    restart: always
    devices:
      - /dev/ttyHead:/dev/ttyHead
    ports:
      - 127.0.0.1:28053:8000
    command: ["-device", "/dev/ttyHead", "-protocol", "jjrobot", "-log", "info"]
  fileman-el:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/fileman:1.1.2
    container_name: fileman-el
    restart: always
    volumes:
      - /media/jjrobot-le-media:/storage
    environment:
      - ROOT=/storage
