version: "3"

services:
  face-recognition:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/face-recognition:1.2.4-arc
    container_name: face-recognition
    restart: always
    depends_on:
      - camera
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/jjrobot/faces-arc:/face_images
    environment:
      - GODEBUG=netdns=cgo
      - DB_HOST=db
      - DB_PORT=27017
      - DB_USER=robotjj
      - DB_PASS=ROBOTjjROBOT
      - MGO_IMAGE_ROOT=/face_images
      - INSECURE_CAMERA_SERVICE_ADDRESS=camera:8000
      - DEFAULT_ON_FACE_DETECT_INTERVAL=300ms
      - DEFAULT_ON_FACE_SET_FACE_DETECT_INTERVAL=300ms
      - DEFAULT_ON_FACE_SET_FACE_DETECT_CONFIDENCE_MIN=0.6
    mac_address: fc:aa:14:d7:cd:33
