version: "3"

services:
  handsmotion:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/hands-motion:0.1.0-alpha3
    container_name: handsmotion
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyHandsMotion
    environment:
      LOG_LEVEL: debug
    volumes:
      - /etc/localtime:/etc/localtime:ro
