version: "3"

services:
  id_card:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/id_card:1.0.1
    container_name: service-id-card
    restart: always
    privileged: true
    environment:
      - module=zkidm30
    volumes:
      - /etc/localtime:/etc/localtime:ro
