version: "3"

services:
  id_card:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/id_card:1.0.1
    container_name: service-id-card
    restart: always
    privileged: true
    environment:
      - module=zkidm30
    labels:
      - traefik.enable=true
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.frontend.rule=PathPrefix:/idCardService.IDCardService
    volumes:
      - /etc/localtime:/etc/localtime:ro
