version: "3"

services:
  id_card:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/id_card:1.0.2
    container_name: id_card
    restart: always
    privileged: true
    environment:
      - GODEBUG=netdns=cgo
      - module=zkidm30
    volumes:
      - /etc/localtime:/etc/localtime:ro
