version: "3"

services:
  lights:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/lights:1.4.0-alpha
    container_name: lights
    restart: always
    depends_on:
      - hwdevice-head
    environment:
      - mouth_length=0
      - ears_length=0
      - hands_length=62
    volumes:
      - /etc/localtime:/etc/localtime:ro
  hwdevice-head:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/hwdevice:1.0.1
    container_name: hwdevice-head
    restart: always
    environment:
      - COMPATIBLE=1
    devices:
      - /dev/ttyHead:/dev/ttyHWDevice
  fileman-el:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/fileman:1.1.2
    container_name: fileman-el
    restart: always
    volumes:
      - /media/jjrobot-le-media:/storage
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ROOT=/storage
