version: "3"

services:
  motion:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/motion:1.1.1
    container_name: service-motion
    restart: always
    environment:
      - module=v1
      - HEAD_X_AXIS_OFFSET=0
      - HEAD_X_AXIS_LEFT=75
      - HEAD_X_AXIS_CENTER=135
      - HEAD_X_AXIS_RIGHT=195
      - HEAD_Y_AXIS_OFFSET=0
      - HEAD_Y_AXIS_TOP=120
      - HEAD_Y_AXIS_MIDDLE=135
      - HEAD_Y_AXIS_BOTTOM=150
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.backend=motion
      - traefik.frontend.rule=PathPrefix:/api/v2/motion
    volumes:
      - /etc/localtime:/etc/localtime:ro
  gserial-motion:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/grpc_serial:1.1.0
    container_name: gserial-motion
    restart: always
    devices:
      - /dev/ttyMotion:/dev/ttyMotion
    ports:
      - 127.0.0.1:28051:8000
    command: ["-device", "/dev/ttyMotion", "-protocol", "jjrobot", "-log", "info"]
