version: "3"

services:
  nav:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/nav:2.4.3-bks
    container_name: nav
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/boocax/server/repo:/mapRepo
