version: "3"

services:
  nav:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/nav:2.4.0-bks.alpha.7
    container_name: nav
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_LEVEL=debug
