version: "3"

services:
  nav:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/nav:2.2.7
    container_name: service-nav
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.port=9000
      - traefik.http.backend=nav
      - traefik.http.frontend.rule=PathPrefix:/api/v2/nav
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.backend=nav
      - traefik.grpc.frontend.rule=PathPrefix:/navService.NavController
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - module=jjmgt
  gserial-chassis:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/grpc_serial:1.1.0
    container_name: gserial-chassis
    restart: always
    devices:
      - /dev/ttyChas:/dev/ttyChas
    ports:
      - 127.0.0.1:28055:8000
    command: ["-device", "/dev/ttyChas", "-protocol", "jjrobot", "-log", "info"]
