version: "3"

services:
  nav:
    image: jjrobot/nav
    container_name: service-nav
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - module=jjmgt
  gserial-chassis:
    image: jjrobot/grpc_serial
    container_name: gserial-chassis
    restart: always
    devices:
      - /dev/ttyChas:/dev/ttyChas
    ports:
      - 127.0.0.1:28055:8000
    command: ["-device", "/dev/ttyChas", "-protocol", "jjrobot", "-log", "info"]
