version: "3"

services:
  network:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/network:1.3.0
    container_name: service-network
    restart: always
    environment:
      - module=wifi360
      - device=10.10.10.1:80
      - p=andy4wifi
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.backend=network
      - traefik.frontend.rule=PathPrefix:/api/v2/network
    volumes:
      - /etc/localtime:/etc/localtime:ro
