version: "3"

services:
  network:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/network:1.3.0
    container_name: service-network
    restart: always
    environment:
      - module=openwrt
      - device=10.10.10.1:80
      - p=andy4wifi
    labels:
      - traefik.enable=true
      - traefik.http.port=9000
      - traefik.http.backend=network
      - traefik.http.frontend.rule=PathPrefix:/api/v2/network
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.backend=network
      - traefik.grpc.frontend.rule=PathPrefix:/networkService.NetworkService
    volumes:
      - /etc/localtime:/etc/localtime:ro
