version: "3"

services:
  power:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/power:1.1.0
    container_name: power
    restart: always
    depends_on:
      - hwdevice-power
      - nav
    environment:
      - module=base
    volumes:
      - /etc/localtime:/etc/localtime:ro
  hwdevice-power:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/hwdevice:1.0.1
    container_name: hwdevice-power
    restart: always
    devices:
      - /dev/ttyPower:/dev/ttyHWDevice
