version: "3"

services:
  power:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/power:1.3.2
    container_name: power
    restart: always
    depends_on:
      - hwdevice-power
      - nav
    environment:
      - GODEBUG=netdns=cgo
      - module=base
    volumes:
      - /etc/localtime:/etc/localtime:ro
  hwdevice-power:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/hwdevice:1.0.5
    container_name: hwdevice-power
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyPower:/dev/ttyHWDevice
