version: "3"

services:
  power:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/power:1.0.3
    container_name: power
    restart: always
    depends_on:
      - gserial-power
    environment:
      - module=base
    labels:
      - traefik.enable=true
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.frontend.rule=PathPrefix:/powerService.PowerService
    volumes:
      - /etc/localtime:/etc/localtime:ro
  gserial-power:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/grpc_serial:1.1.1
    container_name: gserial-power
    restart: always
    devices:
      - /dev/ttyPower:/dev/ttyPower
    ports:
      - 127.0.0.1:28054:8000
    command: ["-device", "/dev/ttyPower", "-protocol", "jjrobot", "-log", "info"]
