version: "1"
requirements:
  - file:
      src: https://s.jj-robot.com/install/jjrobotctl
      dst: /usr/local/bin/jjrobotctl
      x_perm: true
  - file:
      src: https://s.jj-robot.com/install/99-jjrobot-vol-serial.rules
      dst: /etc/udev/rules.d/99-jjrobot-vol-serial.rules
  - image:
      image: registry.cn-shenzhen.aliyuncs.com/jjrobot/jjrobotd:2.3.0-rc2
      rename: jjrobot/jjrobotd
