version: "3"

services:
  sensor:
    image: jjrobot/sensor
    container_name: service-sensor
    restart: always
    environment:
      - module=v2
    volumes:
      - /etc/localtime:/etc/localtime:ro
  gserial-sensor:
    image: jjrobot/grpc_serial
    container_name: gserial-sensor
    restart: always
    devices:
      - /dev/ttySensor:/dev/ttySensor
    ports:
      - 127.0.0.1:28052:8000
    command: ["-device", "/dev/ttySensor", "-protocol", "jjrobot", "-log", "info"]
