version: "3"

services:
  sensor:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/sensor:2.2.1
    container_name: service-sensor
    restart: always
    environment:
      - module=v2
    labels:
      - traefik.enable=true
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.frontend.rule=PathPrefix:/sensorService.SensorService
    volumes:
      - /etc/localtime:/etc/localtime:ro
  gserial-sensor:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/grpc_serial:1.1.0
    container_name: gserial-sensor
    restart: always
    devices:
      - /dev/ttySensor:/dev/ttySensor
    ports:
      - 127.0.0.1:28052:8000
    command: ["-device", "/dev/ttySensor", "-protocol", "jjrobot", "-log", "info"]
