version: "3"

services:
  sensor:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/sensor:2.4.0-hwdevice
    container_name: sensor
    restart: always
    depends_on:
      - hwdevice-sensor
      - hwdevice-head
    environment:
      - module=v2
    labels:
      - traefik.enable=true
      - traefik.grpc.protocol=h2c
      - traefik.grpc.port=8000
      - traefik.grpc.frontend.rule=PathPrefix:/sensorService.SensorService
      - traefik.http.port=9000
      - traefik.http.frontend.rule=Method:GET,POST,PATCH,PUT,DELETE;PathPrefix:/api/v2/sensor
      - traefik.http.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*
    volumes:
      - /etc/localtime:/etc/localtime:ro
  hwdevice-sensor:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/hwdevice:1.0.0
    container_name: hwdevice-sensor
    restart: always
    devices:
      - /dev/ttySensor:/dev/ttyHWDevice