version: "3"

services:
  speech:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/speech:2.1.5
    container_name: service-speech
    restart: always
    environment:
      - module=aiuiv2
      - wifi_ssid=
      - wifi_pwd=
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.backend=speech
      - traefik.frontend.rule=PathPrefix:/api/v2/speech
    volumes:
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttySpeech:/dev/ttyAiuiV2
