version: "3"

services:
  speech:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/speech:4.0.0
    container_name: speech
    restart: always
    privileged: true
    environment:
      - GODEBUG=netdns=cgo
      - module=aiuiv2
      - wifi_ssid=
      - wifi_pwd=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttySpeech:/dev/ttyAiuiV2
