version: "3"

services:
  speech:
    image: registry.cn-shenzhen.aliyuncs.com/jj-robot/speech:4.0.0_baidu_dev1
    container_name: speech
    restart: always
    privileged: true
    environment:
      - MIC_NAME=bothlent
      - LOG_LEVEL=debug
      - GODEBUG=netdns=cgo
      - module=aiuiv2
      - wifi_ssid=
      - wifi_pwd=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/snd:/dev/snd