version: "3"

services:
  speech:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/kaldi:cn
    container_name: speech
    restart: always
    ports:
      - "2700:2700"
    environment:
      - GODEBUG=netdns=cgo
      - module=aiuiv2
      - wifi_ssid=
      - wifi_pwd=
    volumes:
      - /etc/localtime:/etc/localtime:ro
