version: "3"

services:
  xcode_scanner:
    image: jjrobot/xcode_scanner
    container_name: service-xcode-scanner
    restart: always
    environment:
      - module=nlfm25
    volumes:
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyXcodeScanner:/dev/ttyXcodeScanner
