version: "3"

services:
  xcode_scanner:
    image: registry.cn-shenzhen.aliyuncs.com/jjrobot/xcode_scanner:1.0.2
    container_name: xcode_scanner
    restart: always
    privileged: true
    environment:
      - GODEBUG=netdns=cgo
      - module=nlfm25
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyXcodeScanner:/dev/ttyXcodeScanner
